static/signin.css
static/signup.css
templates/signin.html
templates/signup.html

- Added .css file
- Completed HTML
- Linked Sign Up and Log In

Added Sign Up UI

---

scheduleGenerator.py

Primitive implementation of the scheduling algo. Will need to edit the logic behind how we choose employees for shifts based on their maxHours.

Primitive scheduling algo

---

static/availability.js
static/schedule.css
templates/unavailability.html

- Added button icons
- Created better sectioning
- Adjusted color pallete
- Moved Selections to sidebar

Redesigned Availability for better UX w/ Bootstrap

---

scheduleGenerator.py
views.py

Created an endpoint for schedule generation. Nothing prints on the screen yet, but successfully retrieves availability from the backend and outputs schedule to terminal

created endpoint for schedule generation

---

static/schedule.css
templates/schedule.html

- Altered Schedule's appearance to match Availability
- Added Summary section
- Fixed color pallete, added icons, etc.
- Overall improved appearance

Updated Schedule for improved UX w/ Bootstrap

---

website/templates/schedule.html
website/templates/unavailability.html

- Added shadow-sm to sidebar and main card
- Added special shadow w/o sides to header

Added Drop Shadows to Schedule and Availability

---

website/views.py

-Fixed to where name appears in Welcome message of Availability

Name fix in Availability

---

website/static/availability.js
website/static/schedule.css
website/static/schedule.js
website/templates/schedule.html
website/templates/unavailability.html

- New dropdown button
- Added schedule.js
- Added js print functionality

Added print functionality to Other button

---

website/static/schedule.js
website/templates/schedule.html
website/views.py

-- Uses ISO format!!
-- Pulls from the database based on week selection
-- Updates grid with shift
-- Searches assignments based on employee id and week 
-- Added weekly button increment/decrement support
-- Updated .js, HTML, and views accordingly

Add per week support to schedule

---

website/static/signin.css
website/static/signup.css
website/templates/schedule.html
website/templates/signin.html
website/templates/signup.html
website/templates/unavailability.html

--Added Shadow and Secondary Color to Footer
--Added Footer to Signin and Signup
--Fixed Coloring on Header Buttons in Signin and Signup

Fixed Footer and Header Buttons (signin/signup)

---

website/auth.py
website/templates/signin.html
website/templates/signup.html

--Add necessary flash message to sign in and sign up --Fixed flash appearance

Fixed Flash messages

---

website/__init__.py
website/auth.py
website/templates/signin.html

-- Connected to auth.py
-- Changed config to remember for 30 days

Added Support for Remember Me Checkbox

---

website/views.py

Fixed Missing Name in Schedule

---

website/static/availability.js
website/templates/unavailability.html

--Chevron buttons now update week
--Removed shadow when clicked
--Updated HTML and .js

Added increment/decrement week functionality

---

website/templates/schedule.html
website/templates/unavailability.html
website/views.py

-- Reworked Notifcations and Profile into List
-- Added lables for name and hourly to profile
-- Added sign out
-- Added divider to notifcations
-- Updated HTML and views.py

Added Dropdown for Profile Info and Sign out

---

website/static/schedule.js
website/templates/schedule.html
website/templates/unavailability.html
website/views.py

-- Weekly wage -> employee hourly * hours
-- Hours -> shifts length (handles overlap and duplicates) -- Added hourly to profile info

Added weekly wage and hours calculation

---

website/static/availability.js
website/static/schedule.css
website/static/schedule.js
website/templates/events.html
website/templates/schedule.html
website/templates/unavailability.html

--Dynamic widths, font sizes, etc.
--Fixed NaN bug with Wages

Added support for layout changes

---

website/auth.py

--If user is authenticated (or "remembered"), login and signup pages redirect to schedule

Added redirect to schedule if user is signed in

---

website/static/availability.js
website/static/schedule.css
website/static/schedule.js
website/templates/schedule.html
website/templates/unavailability.html
website/views.py

--Created UI for notifications w/ messsage, read status, and timestamp 
--Added endpoint for clearing notification in DB
--Added endpoint for marking notifcations as read in DB --Added endpoint for loading notifications

Added notification loading, clearing, and marking

---

website/static/availability.js
website/static/schedule.css
website/templates/unavailability.html
website/views.py

-- "Nothing to see here..." message added to notifications and unavailability

Added messages for empty lists

---

website/static/availability.js
website/templates/unavailability.html
website/views.py

-- For each button in menu added confirmation modal 
-- Added autofill functionality w/ clear

Added autofill and modal confirmations

---

website/static/availability.js

Added validation to addUnavailability()

---

website/static/availability.js
website/static/schedule.js

Added improved styling to schedule and unavailability cells
-- Better text handling
-- More professional and consistent look

Better cells

---

website/static/schedule.css
website/static/signin.css
website/static/signup.css
website/templates/schedule.html
website/templates/signin.html
website/templates/signup.html
website/templates/unavailability.html

-- New borders, backgrounds, hover features, icons, placements, etc. 
-- Improved UX -> appearance and feel

Upgraded button appearances

---

website/templates/unavailability.html

-Added one line of CSS to make the selection section scrollable

Added scrollability for the selection section

---

website/static/availability.js
website/templates/unavailability.html

-- Redesigned the selections list item
-- Fixed times features in add()

Improved unavailability list item appearance

---

website/static/admin.js
website/templates/admin.html
website/views.py

-doesn't allow admin to schedule past weeks
-checks admin list before calling endpoint
-checks to see if a schedule is already generated for given week before approving proposed schedule

Validation logic for admin

---

website/static/events.js
website/static/schedule.css
website/templates/events.html
website/views.py

-- Added loading events
-- New hour grid
-- Updated HTML based on unavailability

Added Events Page Template

---

website/scheduleGenerator.py
website/static/admin.js
website/views.py

Updated scheduling algo, that favors employees who haven't reached their min hours, before considering distance from max. Also displays names on generated schedule.

committing new scheduling algo

---

website/views.py

--Added get, add, and clear endpoints for events
--Should only be available to admins
--Mirror to unavailability

Added Events endpoints

---

website/views.py

Deleted duplicate event endpoint

---

website/views.py

-- Now takes name, host, and description

Fixed add event endpoint

---

website/static/availability.js
website/static/events.js
website/templates/events.html
website/views.py

Started implementing front-end functionality for events page

event page changes

---

website/static/events.js
website/templates/events.html
website/views.py

-- Supports deletion and updating list
-- Fixed grid appearance

Added events list and fix

---

website/static/events.js
website/templates/events.html
website/views.py

-- Start and end time were equivalent because endpoint was passing start for both

Solved problem where event wasn't appearing

---

website/static/events.js
website/templates/events.html

--Events selections vs. assign is fixed

Fixed concurrent lists

---

website/views.py

Ensuring that a user can't claim the same event twice

Preventing double event assignment

---

website/static/availability.js
website/views.py

Fixed where Sundays were not included

---

website/static/availability.js
website/static/events.js
website/static/schedule.css
website/static/schedule.js
website/templates/schedule.html

--Slots now cross borders to fill the schedule
--Added to schedule, unavailability, and events
--Slots are bubbles with the times

Improved cell displays

---

website/views.py

--If not admin you cannot access add or clear events, admin, generate or approve schedule endpoints

Added isAdmin checks to endpoints:

---

website/models.py
website/static/admin.js
website/static/availability.js
website/static/events.js
website/static/schedule.css
website/templates/admin.html
website/templates/events.html
website/templates/schedule.html
website/templates/unavailability.html
website/views.py

--Created link in header if admin
--Added dynamic layout
--Show full schedule if admin w/ endpoint
--Prevent schedule generation for previous weeks
--Admin grid fix w/ better look

Overhauled admin page

---

website/static/schedule.css

Changed the css for the notification dot when the page is less then 1200 pixels. This was in schedule.css

fixed notification dot when page is smaller

---

website/views.py

Ensuring someone who is working at same time as a shift trade can't claim it

error handling for shift trading
